name: ""
title: null
email: thmscmpgn@gmail.com
description: >- # This shows up in Google search results
  Undergraduate Physics & Math Student at Austin Peay State University. 
  Aspiring Computational Physicist specializing in Fluid Dynamics and Photonics.
  
# Site Settings
url: "https://THMSCMPG.github.io"
baseurl: "" 

# Build Settings
markdown: kramdown
theme: minima # Or your chosen theme like 'minimal-mistakes'
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Math Rendering
kramdown:
  math_engine: mathjax
