name: ""
title: Thomas Campagna
email: thmscmpgn@gmail.com
description: >- # This shows up in Google search results
  Undergraduate Physics & Math Student at Austin Peay State University. 
  Aspiring Computational Physicist specializing in Fluid Dynamics and Photonics.
  
# Site Settings
url: "https://THMSCMPG.github.io"
baseurl: ""

# Build Settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Math Rendering
kramdown:
  math_engine: mathjax

# Navigation
header_pages:
  - README.md
  - projects.md
